name: Deploy_to_Heroku
on:
  push:
    branches:
      - trunk
jobs:
  heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "liatriointerview" #Must be unique in Heroku
          heroku_email: "evanmdrake@icloud.com"
          usedocker: true
